name: extension_enabler
description: Enable web as extension for chromium based browsers.
version: 1.0.0
homepage: https://github.com/narayann7/ExtensionEnabler

environment:
  sdk: ">=2.18.6 <3.0.0"

dev_dependencies:
  lints: ^2.0.0
dependencies:
  args: ^2.3.1
  html: ^0.15.1
  path: ^1.8.0
executables:
  extension_enabler: start
