name: extension_enabler
description: A command line tool that enables flutter web app as chromium based extension with simple commands.
version: 1.0.2
homepage: https://github.com/narayann7/ExtensionEnabler

environment:
  sdk: ">=2.18.6 <3.0.0"

dev_dependencies:
  lints: ^2.0.0
dependencies:
  args: ^2.3.1
  html: ^0.15.1
  path: ^1.8.0
